<h1>Problem 1: Factorials using numpy</h1>
<li><b>prod</b> A numpy function that returns the product of all elements in an array
<li><b>cumprod</b> A numpy function on an ndarray of size n that returns an array of size n where each element i is the product of all elements from 0 to i


In [1]:
"""
Replace pass with the code that uses ndarray, prod and cumprod 
to calculate the factorial of n

The function should take an integer as an argument and return an integer

"""
def factorial(n):
    import numpy as np
    n = int(n)         # Assure that input is an integer in case input incorrectly.
    n_factorial = 1    # initialize as output as 1 in case the input is 0 (since 0! = 1).
    
    if(n==0):
        n_factorial = n_factorial   # Since 0! = 1 
    elif(n<0):
        return print(ValueError,'Undefined; the argument n must be a nonnegative integer.')
    else:
        n_array = np.arange(n+1)
        #n_array = np.array(n_array,'int')  
        n_array = n_array[1:n+1]   ## remove 0 from the array (o.w., product will collapse to 0)
        n_factorial = np.prod(n_array)
    
    return n_factorial



In [2]:
## Testing the function to verify it returns the correct answer for varying input values
print("0! = ",factorial(0))
print("1! = ",factorial(1))
print("2! = ",factorial(2))
print("3! = ",factorial(3))
print("4! = ",factorial(4))
print("5! = ",factorial(5))

0! =  1
1! =  1
2! =  2
3! =  6
4! =  24
5! =  120


In [3]:
 ## Verifying error message is returned when input is a negative integer.
factorial(-1)  

<class 'ValueError'> Undefined; the argument n must be a nonnegative integer.


In [4]:
"""
Replace pass with the code that uses ndarray, prod and cumprod to 
calculate the factorials of all values from 1 to n

The function should take an integer as an argument and return an ndarray
of size n 

"""

def all_factorials(n):
    import numpy as np
    if(n==0):
        array_factorial = 1   # Since 0! = 1 
    elif(n<0):
        return print('Undefined; the argument n must be a nonnegative integer.')
    else:
        n_array = np.arange(n+1)
        n_array = np.array(n_array,'int') # Assure that input is an integer in case input incorrectly.
        n_array = n_array[1:n+1]          # remove 0 from the array (o.w., product will collapse to 0)
        array_factorial = np.cumprod(n_array)
    
    return array_factorial


In [5]:
# Testing function to verify

all_factorials(5)

array([  1,   2,   6,  24, 120])

<h1>Problem 2: Percent changes</h1>
Write a function that constructs an ndarray from data in a file and 
returns a 1-period percent change on an ndarray after removing any nan values. Your function must make use of the following functions:
<li>np.genfromtxt: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.genfromtxt.html
<li>np.diff: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diff.html
<li>np.isnan: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.isnan.html

<p>Test your function out using the attached apple.csv file. Your function can assume that the file structure is (date,price)

<p>Note that percent change is defined as (p(t)-p(t-1))/p(t-1)

<b>Example:</b><br>
If the data array is: np.array([1,2,np.NaN,4,8,np.NAN])
<br>
The output array should be<br>
array([ 1.,  1.,  1.])


In [6]:
def get_pct_changes(file_name):
    import numpy as np
    
    raw_data = np.genfromtxt(file_name,delimiter=",")
    missing_data = np.isnan(raw_data)
    clean_data = raw_data[~(missing_data)]
    diff = np.diff(clean_data)
    N = len(clean_data)
    percent_change = diff/clean_data[:N-1]
    
    return percent_change

In [7]:
## Testing function on the apple.csv file

get_pct_changes('apple.csv')

array([-0.05217305, -0.07339571,  0.02475207, ..., -0.00977899,
       -0.00882215,  0.01720356])

<h1>Problem 3: Pandas Grouping</h1>
Write a program that reads timeseries pricing data from a file into a pandas dataframe and then groups the data as follows:
<li>Adds a column, one-day percent change to the file 
<li>Groups the data into four categories:
<ul>
<li>"High+" if the percent change is greater than 2.5%
<li>"Low+" if the percent change is positive and less than or equal to 2.5% 
<li>"Low-" if the percent change is negative but greater than or equal to -2.5%
<li>"High-" if the percent change is less than -2.5%
</ul>
<li>Report the size and the mean of each of the groups



In [8]:
datafile = "apple.csv"
import pandas as pd
df = pd.read_csv('apple.csv',na_values='null')

# Adding one-day percent change column to dataframe
df['One-Day Percent Change'] = df['Adj Close'].pct_change()

# Functional grouping into four categories
def GroupData(df,ind,col):
    #df['One-Day Percent Change'] = df[col].pct_change()
    
    if df[col].loc[ind] > 0.025:      
        return 'High+'
    elif (df[col].loc[ind] > 0) and (df[col].loc[ind] <= 0.025):
        return 'Low+'
    elif (df[col].loc[ind] < 0) and (df[col].loc[ind] >= -0.025):
        return 'Low-'
    elif df[col].loc[ind] < -0.025:
        return 'High-'
    else:
        return None

grouped_data = df.groupby(lambda x: GroupData(df, x, 'One-Day Percent Change'))

grouped_data
print(grouped_data.size())
print(grouped_data.mean())

High+    1391
High-    1210
Low+     3170
Low-     3140
dtype: int64
       Adj Close  One-Day Percent Change
High+   8.652295                0.045705
High-   8.289065               -0.044220
Low+   26.292799                0.011020
Low-   24.183470               -0.011171
