<h2>Three Types of Indexing Supported </h2>

In [1]:
import numpy as np

a = np.arange(1,20,3) 
b = np.arange(15)
ax = np.array(b.reshape(3,5))
print("a = ",a,"\n")
print ("ax = ","\n\n", ax)

a =  [ 1  4  7 10 13 16 19] 

ax =  

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


<h3>field access (1-d array)</h3>

In [3]:
a[[1,4]] 

array([ 4, 13])

<h3>field access (multi-dim array)</h3>

In [4]:
rows = np.array([0,2])
cols = np.array([1,4])
ax[rows,cols] 

array([ 1, 14])

<h3>basic slicing (1-d array)</h3>

In [5]:
a[2:7:2]   # a[start : stop : step-size]

array([ 7, 13, 19])

<h3>basic slicing (multi-dim array)</h3>

In [6]:
ax[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

<h3>advanced indexing using arrays</h3>

In [7]:
ay = np.array([[2,4],[1,3]])
a[ay]

array([[ 7, 13],
       [ 4, 10]])

In [22]:
az = np.array([[0,2],[1,0]])
# ax[az]

In [27]:
i = np.array([1,0])
j = np.array([1,2])
k = np.array([[1,0],[0,2]])  # a list of two lists
# ax[i] 
# ax[j]
# ax[i,j]       # pass two arrays here, so it pulls individual elements
# ax[0:1,:]     #only includes row 0 since it doesn't include the higher end (& includes all columns)
# ax[[1],[0,2]]  # indexed rows and columns don't have to have the same number of elements,
               # it just applies that one row to all the column indices: ax[[1,0],[1,2]]
ax[k]  # k is like a list of two lists. It's a single array with arrays inside it.
       # because you're only passing one array, it treats the indices are indices for the rows

array([[[ 5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4]],

       [[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]])

In [32]:
ax[i,j]

array([6, 2])

<h3>getting the corners of the array as a 2-d array</h3>

In [33]:
ax[k]

array([[[ 5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4]],

       [[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]])

In [49]:
rows2 = np.array([[0,0],[2,2]])
cols2 = np.array([[0,4],[0,4]])
ax[rows2,cols2]                # [[0  0]
                               #  [0  4]
                               #  [2  2]
                               #  [0  4]]

array([[ 0,  4],
       [10, 14]])

<h3>getting corners using slicing</h3>

In [19]:
ax[0:3:2,0:5:4]

array([[ 0,  4],
       [10, 14]])

<h3>Can combine slice for row and advance indexing for column</h3>

In [20]:
ax[1:3,[2,3,4]] 

array([[ 7,  8,  9],
       [12, 13, 14]])

In [3]:
np.random.normal(size=10)

array([ 1.18593618, -1.74900727,  0.24423427, -0.89283381, -0.08138813,
       -0.65213849,  0.07376094,  0.95650705, -0.21152717,  0.67154204])