<h2>Three Types of Indexing Supported </h2>

In [34]:
import numpy as np

a = np.arange(1,20,3) 
b = np.arange(15)
ax = np.array(b.reshape(3,5))
# print("a = ",a,"\n")
# print ("ax = ","\n\n", ax)

<h3>field access (1-d array)</h3>

In [35]:
# a[[1,4]] 

<h3>field access (multi-dim array)</h3>

In [36]:
rows = np.array([0,2])
cols = np.array([1,4])
# ax[rows,cols] 

<h3>basic slicing (1-d array)</h3>

In [37]:
# a[2:7:2]

<h3>basic slicing (multi-dim array)</h3>

In [46]:
ax[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

<h3>advanced indexing using arrays</h3>

In [21]:
ay = np.array([[2,4],[1,3]])
# a[ay]

In [22]:
az = np.array([[0,2],[1,0]])
# ax[az]

In [31]:
i = np.array([1,0])
j = np.array([1,2])
k = np.array([[1,0],[0,2]])
# ax[i] 
# ax[j]
# ax[i,j]
# ax[0:1,:]
# ax[[1],[0,2]]
ax[k]

array([[0, 1, 2, 3, 4]])

In [32]:
ax[i,j]

array([6, 2])

<h3>getting the corners of the array as a 2-d array</h3>

In [33]:
ax[k]

array([[[ 5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4]],

       [[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]])

In [49]:
rows2 = np.array([[0,0],[2,2]])
cols2 = np.array([[0,4],[0,4]])
ax[rows2,cols2]

array([[ 0,  4],
       [10, 14]])

<h3>getting corners using slicing</h3>

In [23]:
ax[0:3:2,0:5:4]

<h3>Can combine slice for row and advance indexing for column</h3>

In [24]:
# ax[1:3,[2,3,4]] 