<h1>Python libraries for data analysis</h1>


<li><b><span style="color:blue">Numpy</span></b>: supports numerical and array operations
<li><b><span style="color:blue">Scipy</span></b>: open source library for mathematics and scientific computing
<li><b><span style="color:blue">Pandas</span></b>: supports data manipulation and analysis
<li><b><span style="color:blue">Visualization libraries</span></b>: matplotlib, seaborne, bokeh, plotly, gmplot, and many others provide support for charts and graphs

<h1>numpy</h1>


<h2>Why numpy?</h2>
<li>Multi-dimensional arrays:
<li>Faster and more space efficient than lists 
<li>Can incorporate C/C++/Fortran code
<li>Linear algebra, Fourier transforms, Random number support



#### Constraint of numpy:  In a numpy array, the data type has to be the same

<h2>numpy array</h2>

In [1]:
import numpy as np
ax = np.array([1,2,3,4,5])
print(type(ax))


<class 'numpy.ndarray'>


In [4]:
np.arange(0,1,0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

<li>A numpy array has a data type associated with its elements
<li>and elements need to be of the same data type
<li>But an element could be an 'arbitrarily' complex object

In [3]:
np.array([1,2,'a'])   ## Note that dtype '<U21' is a string data type (one of three string data types).

array(['1', '2', 'a'], dtype='<U21')

In [117]:
np.array([{'a':1,'b':2},4])   ## What is common between a dictionary and an int? Python will
                              ## treat each as an object data type. Python tries to make the
                              ## most specific class data type that is common to both for a 
                              ## numpy array. In this case, the most specific class common to
                              ## both is the 'object' data type class.

array([{'a': 1, 'b': 2}, 4], dtype=object)

<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

<h4>The <i>dtype</i> attribute</h4>
<li>Stores the data type in the array
<li>numpy makes a best guess of the data type

In [6]:
ax = np.array([[1,2,3,4],[5,6,7,8.3]])  ## Example of a 2-dimensional array. 
ax.dtype                                ## Because of the element 8.3, it casts all other 
                                        ## elements to a float object

dtype('float64')

In [7]:
ax

array([[1. , 2. , 3. , 4. ],
       [5. , 6. , 7. , 8.3]])

In [121]:
ax = np.array([{'a':1,'b':2},4])
ax.dtype   ## Note: dtype = 'O' denotes the object data type

dtype('O')

In [8]:
x=['1','2','3']    
xi = np.array(x,'int')      # create array of int data types from x
xf = np.array(x,'float')    # create array of float data types from x
xs = np.array(x,'str')      # create array of str data types from x
print(xi,xf,xs,sep='\n')

[1 2 3]
[1. 2. 3.]
['1' '2' '3']


<li>The <i>astype</i> function converts from one type to another


In [10]:
ax = np.array([1,2,3,'4'])
print(ax.dtype)
ax.astype(int)

<U21


array([1, 2, 3, 4])

In [125]:
mx = np.array([1,2,3,'4'])
print(mx.dtype)
mx.astype(int)

<U21


array([1, 2, 3, 4])

In [11]:
ay = ax.astype(np.float128)
print(ay)
ay.dtype

[1. 2. 3. 4.]


dtype('float128')

<h2>Basic operations</h2>

<h4>statistical operations</h4>

In [12]:
x = np.array([13,24,21.2,17.6,21.7],'float')
print(x.sum(),x.mean(),x.std(),sep='\n')

97.50000000000001
19.500000000000004
3.8429155598321434


<h4>arrray arithmetic operations</h4>
<li><b>Important</b>: Arrays must be the same size!

In [127]:
x = np.array([13,24,21.2,17.6,21.7],'float')
y = np.array([1,3,4,7,2],'float')
x - y

array([12. , 21. , 17.2, 10.6, 19.7])

In [14]:
x+y

array([14. , 27. , 25.2, 24.6, 23.7])

In [15]:
x*y

array([ 13. ,  72. ,  84.8, 123.2,  43.4])

In [16]:
x/y

array([13.        ,  8.        ,  5.3       ,  2.51428571, 10.85      ])

<h2>Multi-dimensional arrays</h2>

In [131]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]  ## array with 3 rows and 6 columns
ax=np.array(x,float)
print(ax)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]


<h3>Indexing</h3>

In [132]:
ax[1,3] #indexing  (2nd row, 4th column)

13.0

<h3>Slicing</h3>

In [133]:
ax[1:3,2:4]   
#Intersection between ax[1:3,:] and ax[:,2:4]
#Start at row 1, stop at row 2; start at column 2, stop at column 3

array([[12., 13.],
       [22., 23.]])

<h3>Reshaping</h3>
<li>nd arrays can be reshaped as long as the total dimensionality is unchanged


In [20]:
print(ax.shape)
ax.reshape(9,2)
#ax.reshape(10,3)

(3, 6)


array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [10., 11.],
       [12., 13.],
       [14., 15.],
       [20., 21.],
       [22., 23.],
       [24., 25.]])

<h3>Creating nd arrays</h3>

<h4>Using the <i>array</i> function</h4>

In [21]:
data = [[0,1,2,3,4],[5,6,7,8,9]]
data_array = np.array(data)
data_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<h4>Using initializers</h4>

<li>The <i>arrange</i> (array range) function


In [22]:
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)])
print(ay)
ax.dtype

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


dtype('int64')

In [23]:
ax = np.arange(10)**2
print(ax)

[ 0  1  4  9 16 25 36 49 64 81]


<li>The <i>ones</i> function creates an array of 1s (floats)

In [24]:
ax = np.ones(10)
print(ax)
ax.dtype

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


dtype('float64')

In [25]:
ax = np.array([[1,2,3,4],[5,6,7,8]])
ay = np.ones_like(ax)  ## creates ones array of the same shape as the array in the argument
ay

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:

ay = np.zeros_like(ax)
ay

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

<li>The <i>identity(n)</i> function creates an identity matrix of order n

In [27]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

<li>The function <i>empty</i> creates an "empty" array
<li>Values in the array are "garbage" values

In [28]:
np.empty([2,3],float)  ## create a 2x3 array that is empty. It's not actually empty though
                       ## it initializes with garbage values that cannot be used. It initializes
                       ## to values leftover in that memory location.

array([[ 1.28822975e-231, -1.29074384e-231,  1.48219694e-323],
       [ 0.00000000e+000,  0.00000000e+000,  4.17201348e-309]])

<h3>Matrix multiplication</h3>


In [30]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
ay*2

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [31]:
np.dot(ay,ay.reshape(10,2)) #Dot product

array([[220, 265],
       [220, 265]])

<h2>Lists vs numpy arrays</h2>
<li>Lists are heterogenous. Elements of a list can be of multiple types
<li>Numpy arrays are homogeneous. Elements can be of only one type
<li>Both are mutable
<li>Homogeneity makes indexed access faster and more memory efficient
<li>numpy are optimized for matrix operations
<li>numpy provides random number support


<h3>numpy arrays are homogeneous</h3>

<h3>numpy arrays are faster</h3>

In [32]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
ay = ax.transpose()
print(ax)
print(ay)
np.dot(ax,ay)

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]
[[  0   0]
 [  1   1]
 [  4   8]
 [  9  27]
 [ 16  64]
 [ 25 125]
 [ 36 216]
 [ 49 343]
 [ 64 512]
 [ 81 729]]


array([[ 15333, 120825],
       [120825, 978405]])

<h4>Functionalize this</h4>


In [34]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    ay = ax.transpose()
    import datetime                   # measures the runtime of the computation
    start = datetime.datetime.now()   # Records the current point in time at start of computation
    np.dot(ax,ay)
    end = datetime.datetime.now()     # records time at end of computation
    return end-start           #computes the time required to compute the dot product
    
dotproduct(10)      #Returns time required to compute the dot product of a 10x2 and a 2x10 array

datetime.timedelta(microseconds=16)

<h4>Do the same with python lists</h4>


In [35]:

def dot_product_lists(n):
    x = [x**2 for x in range(n)]       # how to do the same as above, but for a list instead
    y = [x**3 for x in range(n)]  
    ax = [x,y]                         # ax is a list of two lists
    ay = [list(i) for i in zip(*ax)]   # zip() makes element-wise tuples out of the two lists
                                       # this is all done to transpose ax
    import datetime
    start = datetime.datetime.now()
    [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    end = datetime.datetime.now()
    return end-start
    
dot_product_lists(10)

datetime.timedelta(microseconds=21)

<h4>Compare the two</h4>

In [43]:
for n in [10,100,1000,10000,1000000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')   

10	0:00:00.000020	0:00:00.000015
100	0:00:00.000019	0:00:00.000068
1000	0:00:00.000035	0:00:00.000608
10000	0:00:00.000109	0:00:00.008511
1000000	0:00:00.004058	0:00:01.755899


<h3>numpy indexing vs list indexing</h3>
<li>numpy arrays use direct indexing
<li>lists use chained indexing

In [46]:
ax = np.array([1,2,3,4,8,9])
x = [1,2,3,4,8,9]

#Extract the first and last elements from the numpy array into a single array
ax[[0,-1]]           ## for a numpy array, you just have to pass the indices once
print(ax[[0,-1]])

#Extract the first and last elements from the list into a new list
[x[0],x[-1]]        ## for a list you have to keep going back for each element

[1 9]


[1, 9]

<h3>numpy slicing vs list slicing</h3>

In [47]:
ax = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
ax[1:3,1:3]


array([[22, 23],
       [32, 33]])

In [48]:
ax

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [49]:
lx = [[11,12,13,14],[21,22,23,24],[31,32,33,34]]
#HELP!

## Not clear how to slice like this with a list, hence why numpy arrays are 'better' than lists

<h2>batch operations on nd arrays</h2>
<li>numpy arrays allow the application of batch operations on all elements of an array
<li>without having to write a for loop or use an iterator
<li>by <i>vectorizing</i> operations, numpy is much faster than the slow for loop structure of python


<h3>batch: selecting elements using a boolean mask</h3>
<li> A boolean max applies a condition to each element in turn
<li> And returns an array of boolean with
<ul>
<li> True for each value that satisfies the condition
<li> False for every other value

In [50]:
ax = np.array([1,4,7,9,2,3,10,11,34,2])
ax < 7

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

<h4>The mask can be applied as a selection operator on the array

In [51]:
ax[ax<7]   # Extracts all elements that satisfy the condition (the inequality)
           # All elements that correspond to a 'True' value are extracted.
           # This is a way to pull out subsets on an array.

array([1, 4, 2, 3, 2])

<h4>The mask doesn't have to be constructed on the same array</h4>
<li>But the mask and the array should have the same dimensions

In [138]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
names[bonus > 130000]  
## can only do this if the two arrays are the same size and shape (i.e., same dimensions)

array(['Bill', 'Sally'], dtype='<U8')

<h3>batch: arithmentic operations</h3>
<li>+, -, *, /, scalar multiplication do an element by element operation

In [53]:
ax = np.array([[1,2,3],[4,5,6]])
1/ax


array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

<h3>batch: functional artithmetic operators</h3>

In [135]:
ax = np.array([4,9,2,4,0,25,0])
print(np.sum(ax>5))           # counts the number of True values
print(np.count_nonzero(ax))  
print(np.any(ax>10))
print(np.all(ax>0))

2
5
True
False


<h3>Logical operations with numpy</h3>
<li>logical_or
<li>logical_and

In [136]:
np.logical_and(bonus>90000.0, bonus<400000 )

array([ True, False, False,  True, False])

<h4>Boolean operators</h4>
<li>the numpy equivalent of "and" is "&"
<li>the numpy equivalent of "or" is "|"
<li>the numpy equivalent of "not" is "!"


In [139]:
print(np.sum(bonus[(bonus>50000) & (bonus < 200000)]))
print(np.sum(bonus[(names=="Bill") | (names == "Qing")]))
print(np.sum(bonus[(names!="Bill")]))
print(np.sum(bonus[~((names=="Bill") | (names == "Qing"))]))


150135.86
236191.8
632150.55
628259.31


<b>Problem</b> Calculate the mean and median bonus anount for all female employees with bonus less than $100,000

In [57]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
gender = np.array(['M','F','F','F','M'])



<b>Problem</b> Return an nd array containing the named of all female employees with bonus less than $100,000

In [58]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
gender = np.array(['M','F','F','F','M'])


<h3>batch: Selecting elements using where</h3>
<li><i>where</i> function creates a new array using a conditional expression
<li>Somewhat like the if function in an excel spreadsheet

In [142]:
np.where(names == 'Bill',1,0)

array([1, 0, 0, 0, 0])

<h2>axes</h2>
<li>The axis parameter tells numpy which axis to operate along

In [140]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])     #1-dimensional array, shape = (12,)
ax = ax.reshape(3,4)  
print(ax)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [141]:
bx = ax.reshape(2,3,2)
print(bx)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


<h4>sum each column</h4>

In [60]:
ax.sum(axis=0)

array([15, 18, 21, 24])

<h4>sum each row</h4>

In [61]:
ax.sum(axis=1)

array([10, 26, 42])

<h4>sum by depth</h4>

In [62]:
ax=ax.reshape(2,3,2)
ax.sum(axis=2)

array([[ 3,  7, 11],
       [15, 19, 23]])

<h4>add an axis to an array</h4>


In [65]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])   #1-dimensional array, shape = (12,)
print(ax)                                     # If it were a 2D array the shape would be (12,1)
ax[:,np.newaxis]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [2]:
import numpy as np
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])   #1-dimensional array, shape = (12,)
print(ax)
print('')
ax=ax.reshape(3,4)                            #2D array, shape = (3,4)
print(ax)
print('')
print(ax[:,np.newaxis,:])                            #reshaped to a (3,1,4) array
ax[:,np.newaxis,:].shape
#ax[:,:,np.newaxis]                            #reshaped to a (3,4,1) array
#ax[:,:,np.newaxis].shape
#ax[np.newaxis,:,:]                            #reshaped to a (1,3,4) array
#ax[np.newaxis,:,:].shape   
#ax[np.newaxis]                 # also reshapes to (1,3,4)
                                # adds new axis to the front by default

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


(3, 1, 4)

In [88]:
ax[...,np.newaxis].shape

(3, 4, 1)

In [89]:
ax[np.newaxis,...].shape

(1, 3, 4)

<h4>Easy to add n-dimensions to an nd array using newaxis</h4>

In [86]:
ax = ax.reshape(4,3)
ax[np.newaxis,np.newaxis,np.newaxis].shape    # adds new axis to the front by default

(1, 1, 1, 4, 3)

In [90]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
np.where(ax%2==0,1,0)     # if it is a multiple of 2, put a 1, else put 0.

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

<h2>Broadcasting</h2>
<li>arithmetic operations work element by element
<li>so both arrays have to be of the same length
<li><b>broadcasting</b> is used for arithmetic on arrays of different shapes

In [91]:
ax = np.array([1,2,3])
ay = np.array([3,2,1])
ax+ay

array([4, 4, 4])

<li>when one operand is a scalar, numpy works as if it has created a second array
<li>ax + 5 is equivalent to ax + np.array([5,5,5,])
<li>note the "as if" because it doesn't actually do that
<li>instead it <b>broadcasts</b> the 5 to each element of ax
<li>we can do this broadcasting on any dimensional array

In [92]:
ay = np.ones([3,3])
ay

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
ax = np.array([1,2,3])
ax + ay

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

<b>broadcasting</b> won't work when arrays are of incompatible dimensions

In [94]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ay = np.array([3,4,5])
ax + ay

ValueError: operands could not be broadcast together with shapes (12,) (3,) 

<h4>np.newaxis is useful here because we can convert ax into a 2D array</h4>

In [95]:
ax[:,np.newaxis] + ay

array([[ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17]])

In [96]:
#Broadcasting effectively does this:
ax[:,np.newaxis] + np.array([[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5]])

array([[ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17]])

<h4>We could also convert ay into a 2D array</h4>
<li>the result will be different (why?) 

In [97]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ay = np.array([3,4,5])
ax + ay[:,np.newaxis]

array([[ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]])

<h2>Fancy indexing</h2>
<li>numpy let's us work on indexed subsets of an nd array
<li>this lets us construct arbitrary subsets of an nd array in any dimension

In [108]:
ax = np.array([4,3,9,2,1,6])
ay = np.array([2,4])
ax[ay]

array([9, 1])

In [109]:
ay = np.array([[2,4],[1,3]])
ax[ay]

array([[9, 1],
       [3, 2]])

<h4>multi-dimentional indexes</h4>
<li>In a 2-d, index, the index array is used to generate (row_number,col_number) pairs

In [110]:
ax = np.array([[23,34,21,34,22],[33,44,11,29,32],[14,90,10,20,17]])
rows = np.array([0,2])
cols = np.array([1,4])
ax[rows,cols] # [ax[0,1],ax[2,4]]  #returns elements in positions (0,1) and (2,4)

array([34, 17])

<h2>Universal functions</h2>
<li>functions that perform elementwise operations on arrays
<li>fast "wrapper" functions that produce scalar (or lower dimension) results
<li>sqrt, exp, add,maximum, minimum, abs, etc.
<li>https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [111]:
ax = np.array([1,2,3,4,5,6,7],float)
np.sqrt(ax)
np.exp(ax)

array([   2.71828183,    7.3890561 ,   20.08553692,   54.59815003,
        148.4131591 ,  403.42879349, 1096.63315843])

In [112]:
ay = np.arange(10,17)
np.add(ax,ay)
np.maximum(ax,ay)

array([10., 11., 12., 13., 14., 15., 16.])

In [113]:

#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc


In [114]:
import scipy
scipy.nanmean(x)

<ipython-input-114-323a47b69711>:2: DeprecationWarning: scipy.nanmean is deprecated and will be removed in SciPy 2.0.0, use numpy.nanmean instead
  scipy.nanmean(x)


12.5

<h3>Random number support in numpy</h3>

In [160]:
np.random.normal(size=10)
#np.random.normal(size=(100,100))
#np.random.exponential()
#np.random.exponential(1.0,size=(6,3))
#np.random.randint(-10,10,size=(9,9))

array([-0.57984544,  1.07749795,  2.01527657, -1.6746303 ,  2.17404293,
        0.06995509,  0.27890014,  1.86963517,  0.26592964,  0.3441271 ])

In [159]:
np.random.normal(size=100)

array([-0.07504191,  0.03468518,  0.08251165,  1.10562567,  0.04142005,
        0.60342492,  0.16082986, -0.56408602,  0.67957346,  0.48756319,
       -0.7559374 ,  0.71822478,  1.80869499, -0.4135466 ,  0.24571232,
        1.84689391,  0.82061496,  1.20141287, -1.25954935,  1.07413611,
        1.27974674, -0.2846611 , -0.54675281, -0.9179594 ,  0.96534159,
        1.57459982,  0.57656274,  0.00381716,  0.33260385,  0.11443459,
       -0.30826821,  0.66290945, -0.21885024,  0.14833391, -1.95119833,
        1.19967341,  1.94178403, -0.10620175,  2.28444357, -1.44932875,
        1.07718715,  0.38851219, -0.00756727, -0.59238396, -1.00780803,
        0.15916019, -0.60576778, -0.17590228,  0.86156906, -0.34752919,
       -0.06405366,  1.15292326, -0.61838834,  0.40428634,  0.98828116,
       -0.26495661,  1.8456252 ,  0.21069297,  0.45882007,  0.10988982,
        0.55869511, -0.39069574,  0.47955664,  0.87474635,  0.37391199,
        0.4683377 , -1.26379119, -0.72587182,  0.30195881, -0.28

In [145]:
ax = np.arange(18).reshape(6,3)
ax

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [147]:
ax[[2,0],[1,2]]

array([7, 2])

In [154]:
ax = np.arange(18).reshape(6,3)

In [155]:
ax

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [156]:
ax[3:5,1:3]

array([[10, 11],
       [13, 14]])

In [153]:
np.array([[0,1,2],[3,4,5],[6,7,8]])


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.random.randn(10)

array([-0.31479401, -0.83917855, -0.02546244, -1.57087334,  0.32498261,
        0.09929718,  0.95627189,  0.71473372, -0.45133277,  0.20085702])